# constants.py

BLACK = "#000000"
BLUE_98 = "#F7FAFD"
BLUE = "#2C6496"
BLUE_LIGHT = "#D8E6F3"
BLUE_PRESSED = "#17354F"
DARK_BLUE_HOVER = "#1d3e5e"
DARK_GRAY = "#616161"
DARK_RED = "#b50d0d"
DARKEST_BLUE = "#0C1A27"
GRAY = "#808080"
LIGHT_GRAY = "#F2F2F2"
MEDIUM_DARK_GRAY = "#D2D2D2"
MEDIUM_LIGHT_GRAY = "#BDBDBD"
TEAL_ACCENT = "#39C6C0"
TEAL_LIGHT = "#F7FDFC"
TEAL_PRESSED = "#227773"
WHITE = "#FFFFFF"

colors = {
    "BLACK": BLACK,
    "BLUE_98": BLUE_98,
    "BLUE": BLUE,
    "BLUE_LIGHT": BLUE_LIGHT,
    "BLUE_PRESSED": BLUE_PRESSED,
    "DARK_BLUE_HOVER": DARK_BLUE_HOVER,
    "DARK_GRAY": DARK_GRAY,
    "DARK_RED": DARK_RED,
    "DARKEST_BLUE": DARKEST_BLUE,
    "GRAY": GRAY,
    "LIGHT_GRAY": LIGHT_GRAY,
    "MEDIUM_DARK_GRAY": MEDIUM_DARK_GRAY,
    "MEDIUM_LIGHT_GRAY": MEDIUM_LIGHT_GRAY,
    "TEAL_ACCENT": TEAL_ACCENT,
    "TEAL_LIGHT": TEAL_LIGHT,
    "TEAL_PRESSED": TEAL_PRESSED,
    "WHITE": WHITE,
}

# Keep or remove these if your code still needs them:
CURRENT_YEAR = 2024
REFORM_YEARS = [2025, 2026, 2029]
